name: IaC Security Scan Project 2

on:
  push:
    branches:
      - main

jobs:
  iac-scan:
    name: Run IaC Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.5
        with:
          version: v0.69.1
          cache: true

      - name: Run Trivy IaC misconfiguration scan
        run: trivy fs . --scanners misconfig --format table